### ISSUE TITLE
config

### ISSUE THREAD

**Issue by longXboy** [go-kratos/gateway#2]
数据面配置：
- Gateway
  - HTTP
  - GRPC
- Endpoint
  - Host
  - Route
  - Middleware
  - Upstream
- Upstream
  - HeathCheck
  - Discovery
```yaml
gateways:
- port: 80
  address: 0.0.0.0
- port: 443 # TLS is not currently supported
  address: 0.0.0.0

services:
name: some_endpoint
namespace: api.kratos
http:
- methods:
  - POST
  matchs: # path, prefix, regex, queries, headers (and)
  - prefix: /api
  - path: /api/users
  - regex: /api/users/[0-9]+
  - queries:
      username: kratos
  backends: 
  - upstream: some1_upstream
    weight: 20
  - upstream: some2_upstream
    weight: 80
  middlewares:
  - logging: {}
  - metrics: {}
  - retres:
    attempts: 3
    retryOn: [502, 503, 504]

upstreams:
- name: some1_upstream
  health_check:
    timeout: 1s
    interval: 60s
    tcp_health_check: {} # http_health_check, grpc_health_check
  selector:
    discovery:
      region: sh
      zone: sh001
      env: prod
      cluster: group1
- name: some2_upstream
  health_check:
    timeout: 1s
    interval: 60s
    tcp_health_check: {} # http_health_check, grpc_health_check
  selector:
    static:
      - port: 8000
        address: 127.0.0.1
        weight: 100
```

控制面流程：
- Service
- Group
- Endpoint
- Middleware
- Upstream
```
添加服务 
-> 添加分组 -> 域名 -> 中间件
-> 添加接口 -> 路由 -> 中间件
-> 添加上游 -> 服务发现 -> 健康检查
```
