### ISSUE TITLE
改一下默认的 grpc route

### ISSUE THREAD

**Issue by kvii** [go-kratos/gateway#244]
现在用 `kratos new` 创建的工程，grpc 版 helloworld 的默认路由是 "/helloworld.v1.Greeter/SayHello"，多了个 "v1"。所以 gateway 这边最好也改一下。

helloworld grpc 路由：

```go
func _Greeter_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/helloworld.v1.Greeter/SayHello", // <-- 这里
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServer).SayHello(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}
```

gateway 的 config.yaml 还是 "helloworld.Greeter".
```yaml
  - path: /helloworld.Greeter/* # <- 这里
    method: POST
    timeout: 1s
    protocol: GRPC
    backends:
      - target: '127.0.0.1:9000'
    retry:
      attempts: 3
      perTryTimeout: 0.1s
      conditions:
        - byStatusCode: '502-504'
        - byHeader:
            name: 'Grpc-Status'
            value: '14'
```
